---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: "local-secret-store"
