apiVersion: v1
kind: Service
metadata:
  name: adminui
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: adminui
  ports:
    - port: 80
      targetPort: 80
      name: "http"
    - port: 443
      targetPort: 443
      name: "https"