---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tenantstate
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    secretKeyRef:
      name: cosmosdb-secret
      key: url    
  - name: masterKey
    secretKeyRef:
      name: cosmosdb-secret
      key: masterKey
  - name: database
    value: siccar-dev
  - name: collection
    value: tenantstate
