apiVersion: v1
kind: Secret
metadata:
  name: app-api-token
type: Opaque
data:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJEYXByU2VjcmV0IjoiOTg5NGZiZTNkMGExNGE5ZTgxY2VmM2VmMDQifQ.MjL48p-Z6hxjS4TBcCeztYkCnMMWGzZe2LG2EKYv3Oc

# Use in deployment annotation:
# annotations:
#   dapr.io/enabled: "true"
#   dapr.io/app-token-secret: "app-api-token" # name of the Kubernetes secret

# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-api-token
# type: Opaque
# data:
#   token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJEYXByU2VjcmV0IjoiOTg5NGZiZTNkMGExNGE5ZTgxY2VmM2VmMDQifQ.MjL48p-Z6hxjS4TBcCeztYkCnMMWGzZe2LG2EKYv3Oc

# kubectl apply --file dapr-app-token-secret.yaml --namespace $(NAMESPACE)

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJEYXByU2VjcmV0IjoiOTg5NGZiZTNkMGExNGE5ZTgxY2VmM2VmMDQifQ.MjL48p-Z6hxjS4TBcCeztYkCnMMWGzZe2LG2EKYv3Oc

#
#kubectl create secret generic jwt-certificates --from-file=jwt-public.cer --from-file=jwt-private.pfx --dry-run=true  --output=yaml > jwt-secrets.yaml
#--dry-run=client
#kubectl create secret generic app-api-token --from-literal=token=<token>
# jwt.io "your-256-bit-secret"   WMMYUMxHgS6WJrob5zT9txNZ62jXBeaU
#gen'd token via jwt.io ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJEYXByU2VjcmV0IjoiOTg5NGZiZTNkMGExNGE5ZTgxY2VmM2VmMDQifQ.MjL48p-Z6hxjS4TBcCeztYkCnMMWGzZe2LG2EKYv3Oc"
#kubectl create secret generic app-api-token --from-literal=token=<token>
#kubectl create secret generic app-api-token --from-literal=token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJEYXByU2VjcmV0IjoiOTg5NGZiZTNkMGExNGE5ZTgxY2VmM2VmMDQifQ.MjL48p-Z6hxjS4TBcCeztYkCnMMWGzZe2LG2EKYv3Oc" --dry-run=client  --output=yaml > jwt-secrets-foo.yaml
