apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets-vault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "siccarv3-dev"
  - name: azureTenantId
    value: "a2b9ca5b-54e5-437e-866e-bd48bfa6159a"
  - name: azureClientId
    value: "898d91ea-20bb-4b5a-a30e-6c6bd04ad205"
  - name: azureClientSecret
    value : "secretsFile"
  - name: azureClientSecret
    value : "nestedSeparator"    
    

# todo - k8s secret
#   - name: azureClientSecret
#     secretKeyRef:
#       name: "[your_k8s_secret_name]"
#       key: "[your_k8s_secret_key]"
# auth:
#   secretStore: kubernetes