# /*
# * Copyright (c) 2024 Siccar (Registered co. Wallet.Services (Scotland) Ltd).
# * All rights reserved.
# *
# * This file is part of a proprietary software product developed by Siccar.
# *
# * This source code is licensed under the Siccar Proprietary Limited Use License.
# * Use, modification, and distribution of this software is subject to the terms
# * and conditions of the license agreement. The full text of the license can be
# * found in the LICENSE file or at https://github.com/siccar/SICCARV3/blob/main/LICENCE.txt.
# *
# * Unauthorized use, copying, modification, merger, publication, distribution,
# * sublicensing, and/or sale of this software or any part thereof is strictly
# * prohibited except as explicitly allowed by the license agreement.
# */

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bindingaction
spec:
  type: bindings.azure.blobstorage
  version: v1
  initTimeout: 1m
  metadata:
  - name: storageAccount
    value: siccardev
  - name: storageAccessKey
    value: jKvzenLxJ9gKgHtbrYA8wpj83Yyqiw2eZGN5Uv5qfX/Vzk+d1RWv0QBL6YjoNnOtAyOOa0HhldK21ls20VoJgQ==
  - name: container
    value: files
  - name: decodeBase64
    value: true
scopes:
- action-service