apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: validatorstore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
