apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store  #this should be renamed. All environments use the same name but with different type/metadata
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/secretsFile.json
  - name: nestedSeparator
    value: ":"