---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-service
  namespace: default
  labels:
    app: action-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-service
  template:
    metadata:
      labels:
        app: action-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "action-service"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
        dapr.io/app-token-secret: "app-api-token"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
        dapr.io/http-max-request-size: "16"
        dapr.io/config: featureconfig
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-check-path: "/api/actions/healthz"
    spec:
      containers:
      - name: action-service
        image: siccardev.azurecr.io/action-service:latest
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: "#{SERILOG__MINIMUMLEVEL}#"
        - name: TENANTISSUER
          value: "#{TENANTISSUER}#"
        - name: APP__API__TOKEN
          value: "#{APP__API__TOKEN}#"
        - name: DaprSecret
          value: "#{DaprSecret}#"
        - name: MakeSusMgrRequests
          value: "#{MakeSusMgrRequests}#"
        - name: WalletAddress
          value: "#{WalletAddress}#"
        - name: SusConnectorHttpEndpoint
          value: "#{SusConnectorHttpEndpoint}#"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "#{APPLICATIONINSIGHTS_CONNECTION_STRING}#"
        - name: APPLICATIONINSIGHTS__INSTRUMENTATIONKEY
          value: "#{APPLICATIONINSIGHTS__INSTRUMENTATIONKEY}#"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m" 
          limits:
            memory: "2000Mi"
            cpu: "1200m"          
        ports:
        - containerPort: 80
        imagePullPolicy: Always